name: Network Toolkit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10', '3.11']
        exclude:
          # macOS doesn't support Python 3.6
          - os: macos-latest
            python-version: 3.6

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - name: Check requirements
      run: python setup.py
    
    - name: Test import
      run: python -c "import network_toolkit; print('✅ Import successful')"
    
    - name: Test basic functionality (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        timeout 30 python -c "
        from network_toolkit import NetworkToolkit
        toolkit = NetworkToolkit()
        print('Testing DNS...')
        toolkit.check_dns(['google.com'])
        print('Testing local info...')
        toolkit.get_local_info()
        print('✅ Basic tests passed')
        " || echo "⏰ Test timeout (expected)"
    
    - name: Test basic functionality (Windows)
      if: runner.os == 'Windows'
      run: |
        python -c "
        from network_toolkit import NetworkToolkit
        import signal
        import sys
        def timeout_handler(signum, frame):
            print('⏰ Test timeout (expected)')
            sys.exit(0)
        try:
            signal.signal(signal.SIGALRM, timeout_handler)
            signal.alarm(30)
            toolkit = NetworkToolkit()
            print('Testing DNS...')
            toolkit.check_dns(['google.com'])
            print('Testing local info...')
            toolkit.get_local_info()
            print('✅ Basic tests passed')
        except:
            print('⏰ Test completed')
        "
    
    - name: Test CSV export
      run: |
        python -c "
        from network_toolkit import NetworkToolkit
        toolkit = NetworkToolkit()
        toolkit.get_local_info()
        result = toolkit.logger.export_csv('test_export.csv', 'basic')
        print('✅ CSV export test passed' if result else '❌ CSV export failed')
        "
    
    - name: Test HTML export
      run: |
        python -c "
        from network_toolkit import NetworkToolkit
        toolkit = NetworkToolkit()
        toolkit.get_local_info()
        result = toolkit.logger.export_html('test_report.html', 'summary')
        print('✅ HTML export test passed' if result else '❌ HTML export failed')
        "

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install flake8
      run: pip install flake8
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 network_toolkit.py --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 network_toolkit.py --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics